GitHub Actions follow-up
bluesky/ophyd pull request #954
Opened 2020-12-11 18:50 UTC by danielballan

- [x] Remove Travis-CI and encoded tokens for doctr
- [x] Factor installation of system and Python packages into a standalone
- [x] Make `__version__` set correctly so that the version shown in the documentation is correct. (The issue was that we have to fetch the tags and the most recently tagged commit so that `git describe` works.)
- [x] Extract the name of the repo (`'ophyd'` in this case) from the environment to determine the `destination_dir` for published docs. By avoiding hard-coding the repo name, we make `publish-docs.yml` portable without changes. This is of particular interest because we learned how easy it is to copy `publish-docs.yml` to another repo, not notice that the `destination_dir` needs to be updated, and then overwrite a different project's documentation.

2020-12-11 20:28 UTC, prjemian commented on .github/workflows/docs.yml
> +    - name: Install documentation-building requirements
Can you add a blank line before each new group.  Readability.  It's a preference of mine.

2020-12-11 20:33 UTC, prjemian commented on .github/workflows/docs.yml
> +    - name: Install documentation-building requirements
Also, just learned the hard way to add a `shell` specifier before `run`, to control which shell for the commands to follow.  With no spec, it's `sh -e {0}`.  If conda is used (as hklpy needs it), then `shell: bash -l {0}` should be specified.

My advice on shells comes from the README of this action: https://github.com/conda-incubator/setup-miniconda/tree/8246c3d5d22bc5ca3416ddf4f74b77c2fb1d33d0#IMPORTANT

2020-12-11 20:34 UTC, prjemian commented on .github/workflows/flake8.yml
>          run: |
shell: . . .

2020-12-11 20:37 UTC, prjemian commented on .github/workflows/publish-docs.yml
> +    - name: Set env.REPOSITORY_NAME  # just the repo, as opposed to org/repo
Why not do this very early on?  It becomes available earlier.  Some other repos may want this for an action.

2020-12-11 20:37 UTC, prjemian commented on .github/workflows/testing.yml
> +      - cron: '00 4 * * *'  # daily at 4AM
👍

2020-12-11 20:38 UTC, prjemian commented on .github/workflows/publish-docs.yml
> +        fetch-depth: 1000  # should be enough to reach the most recent tag
🥇

2020-12-11 20:39 UTC, prjemian commented on continuous_integration/scripts/install.sh
> +# Verioneer uses the most recent git tag to generate __version__, which appears
spelling: Versioneer

2020-12-11 20:39 UTC, prjemian requested changes
Changes are minor or style. YMMV

2020-12-11 21:27 UTC, danielballan commented
Thanks for the close read, @prjemian. All suggestions addressed.

2020-12-11 21:29 UTC, prjemian approved these changes

2020-12-11 23:14 UTC, dmgav approved these changes
I see no issues.

2020-12-12 00:36 UTC, dmgav commented
I noticed that by default GH Actions are will cancel all jobs if one of the jobs fails ('fail-fast' mode is ON), which I find very annoying. If this behavior is not wanted, 'fail-fast' mode can be disabled as this: https://github.com/bluesky/bluesky-queueserver/blob/0a5f34a7246cca29babb0c9064d237595f27eba2/.github/workflows/testing.yml#L12

2020-12-12 13:52 UTC, danielballan commented
That makes sense to me. Updated. Thanks, @dmgav.

2020-12-12 19:21 UTC, mrakitin commented
For future reference: https://www.edwardthomson.com/blog/github_actions_6_fail_fast_matrix_workflows.html. That's where we originally found it for the queueserver.

2020-12-14 16:56 UTC, mrakitin approved these changes
Looks good!

I think `fail-fast: false` can be used in every workflow, to override the default behavior.

2020-12-14 16:56 UTC, mrakitin commented on .github/workflows/flake8.yml
> +          flake8
`fail-fast: false` for this file too?

2020-12-14 17:53 UTC, merged